# Generated by Django 2.0 on 2018-11-15 13:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bottomdata',
            name='description',
        ),
    ]
