# Generated by Django 2.0 on 2018-09-13 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20180913_1345'),
    ]

    operations = [
        migrations.CreateModel(
            name='BottomData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=512)),
                ('price', models.CharField(max_length=512)),
                ('color', models.CharField(max_length=512)),
                ('sizes', models.CharField(max_length=512)),
            ],
        ),
        migrations.DeleteModel(
            name='Quote',
        ),
    ]
